#pragma once
#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace ActTagContainer
{	//Native
	ACTIONDEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CharacterMoveAround);
	ACTIONDEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CharacterCameraMoveAround);
	//Ability Input
	ACTIONDEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityTest);
	ACTIONDEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RelaxAttack);
	ACTIONDEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavyAttack);
	ACTIONDEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LockTarget);
	ACTIONDEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Defense);
	ACTIONDEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rolling);
}

